PeriodicTable::Application.routes.draw do
  root to: 'home#index'

  match '/atom_model', to: "home#atom_model"
  match '/classification_four', to: "home#classification_four"
  match '/classification_three', to: "home#classification_three"
  match '/classification_two', to: "home#classification_two"
  match '/classification_one', to: "home#classification_one"
  match '/information', to: "home#information"
  match '/predecessors_works', to: "home#predecessors_works"

  match '/hydrogen', to: "elements#H"
  match '/helium', to: "elements#He"

  match '/lithium', to: "elements#Li"
  match '/beryllium', to: "elements#Be"
  match '/boron', to: "elements#B"
  match '/carbon', to: "elements#C"
  match '/nitrogen', to: "elements#N"
  match '/oxygen', to: "elements#O"
  match '/flourine', to: "elements#F"
  match '/neon', to: "elements#Ne"

  match '/sodium', to: "elements#Na"
  match '/magnesium', to: "elements#Mg"
  match '/aluminium', to: "elements#Al"
  match '/silicon', to: "elements#Si"
  match '/phosphorous', to: "elements#P"
  match '/sulphur', to: "elements#S"
  match '/chlorine', to: "elements#Cl"
  match '/argon', to: "elements#Ar"

  match '/potassium', to: "elements#K"
  match '/calcium', to: "elements#Ca"
  match '/scandium', to: "elements#Sc"
  match '/titanium', to: "elements#Ti"
  match '/vanadium', to: "elements#V"
  match '/chromium', to: "elements#Cr"
  match '/manganese', to: "elements#Mn"
  match '/iron', to: "elements#Fe"
  match '/cobalt', to: "elements#Co"
  match '/nickel', to: "elements#Ni"
  match '/copper', to: "elements#Cu"
  match '/zinc', to: "elements#Zn"
  match '/gallium', to: "elements#Ga"
  match '/germanium', to: "elements#Ge"
  match '/arsenic', to: "elements#As"
  match '/selenium', to: "elements#Se"
  match '/bromine', to: "elements#Br"
  match '/krypton', to: "elements#Kr"

  match '/rubidium', to: "elements#Rb"
  match '/strontium', to: "elements#Sr"
  match '/yttrium', to: "elements#Y"
  match '/zirconium', to: "elements#Zr"
  match '/niobium', to: "elements#Nb"
  match '/molybdenum', to: "elements#Mo"
  match '/technitium', to: "elements#Tc"
  match '/ruthenium', to: "elements#Ru"
  match '/rhodium', to: "elements#Rh"
  match '/palladium', to: "elements#Pd"
  match '/silver', to: "elements#Ag"
  match '/cadmium', to: "elements#Cd"
  match '/indium', to: "elements#In"
  match '/tin', to: "elements#Sn"
  match '/antimony', to: "elements#Sb"
  match '/tellurium', to: "elements#Te"
  match '/iodine', to: "elements#I"
  match '/xenon', to: "elements#Xe"

  match '/caesium', to: "elements#Cs"
  match '/barium', to: "elements#Ba"
  match '/hafnium', to: "elements#Hf"
  match '/tantalum', to: "elements#Ta"
  match '/tungsten', to: "elements#W"
  match '/rhenium', to: "elements#Re"
  match '/osmium', to: "elements#Os"
  match '/iridium', to: "elements#Ir"
  match '/platinum', to: "elements#Pt"
  match '/gold', to: "elements#Au"
  match '/mercury', to: "elements#Hg"
  match '/thallium', to: "elements#Tl"
  match '/lead', to: "elements#Pb"
  match '/bismuth', to: "elements#Bi"
  match '/polonium', to: "elements#Po"
  match '/astaline', to: "elements#At"
  match '/radon', to: "elements#Rn"

  match '/francium', to: "elements#Fr"
  match '/radium', to: "elements#Ra"
  match '/rutherfordium', to: "elements#Rf"
  match '/dubnium', to: "elements#Db"
  match '/seaborgium', to: "elements#Sg"
  match '/bohrium', to: "elements#Bh"
  match '/hassium', to: "elements#Hs"
  match '/meitnerium', to: "elements#Mt"

  match '/lanthanum', to: "elements#La"
  match '/cerium', to: "elements#Ce"
  match '/praseodymium', to: "elements#Pr"
  match '/neodymium', to: "elements#Nd"
  match '/promethium', to: "elements#Pm"
  match '/samarium', to: "elements#Sm"
  match '/europium', to: "elements#Eu"
  match '/gadolinium', to: "elements#Gd"
  match '/terbium', to: "elements#Tb"
  match '/dysprosium', to: "elements#Dy"
  match '/holmium', to: "elements#Ho"
  match '/erbium', to: "elements#Er"
  match '/thulium', to: "elements#Tm"
  match '/ytterbium', to: "elements#Yb"
  match '/lutetium', to: "elements#Lu"

  match '/actinium', to: "elements#Ac"
  match '/thorium', to: "elements#Th"
  match '/protoactinium', to: "elements#Pa"
  match '/uranium', to: "elements#U"
  match '/neptunium', to: "elements#Np"
  match '/plutonium', to: "elements#Pu"
  match '/americium', to: "elements#Am"
  match '/curium', to: "elements#Cm"
  match '/berkelium', to: "elements#Bk"
  match '/californium', to: "elements#Cf"
  match '/einstenium', to: "elements#Es"
  match '/fermium', to: "elements#Fm"
  match '/mendelevium', to: "elements#Md"
  match '/nobelium', to: "elements#No"
  match '/lawrencium', to: "elements#Lr"
end
