PeriodicTable::Application.routes.draw do
  root to: 'home#index'

  match '/atom_model', to: "home#atom_model"
  match '/classification_four', to: "home#classification_four"
  match '/classification_three', to: "home#classification_three"
  match '/classification_two', to: "home#classification_two"
  match '/classification_one', to: "home#classification_one"
  match '/information', to: "home#information"
  match '/predecessors_works', to: "home#predecessors_works"

  match '/hydrogen', to: "elements#H"
  match '/helium', to: "elements#He"
  # match '/lithium', to: "elements#Li"
  # match '/berellium', to: "elements#Be"
  # match '/boron', to: "elements#B"
  # match '/carbon', to: "elements#C"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
  # match '/', to: "elements#"
end
